 apiVersion: v1
 kind: Pod
 metadata:
   name: test-pod  
 spec:
   containers:
     - name: mydb-container
       image: mysql:9.4
       ports:
         - containerPort: 3306
           protocol: TCP
       envFrom: 
         - configMapRef:
             name: config-map-db 
         - secretRef: 
             name: secret-pod 
       volumeMounts:
         - name: mydb-values
           mountPath: /var/lib/mysql
   volumes: 
     - configMap:
         name: config-map-db 
     - secret:
         name: secret-db     
         secretName: secret-pod-db